spring:
  application:
    name: auth-service

  data:
    mongodb:
      # Prefer injecting via env var: MONGODB_URI
      uri: ${MONGODB_URI:mongodb://admin:secret@mongo-db:27017/authDB?authSource=admin}

  jackson:
    serialization:
      indent_output: true

  security:
    jwt:
      # Prefer injecting via env var: JWT_SECRET
      secret-key: ${JWT_SECRET:4748930e83a74df3ec63ab8cefc28684dc1ae4a74ecfe3f2343cee5543af2168}
      token-duration: 1D

server:
  port: ${PORT:7075}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://registry-service:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
