spring:
  application:
    name: auth-service

  data:
    mongodb:
      uri: mongodb://admin:secret@localhost:27017/authDB?authSource=admin

  jackson:
    serialization:
      indent_output: true

  security:
    jwt:
      secret-key: dhRnSCE3s-KPn5fs_qIDGHO0WUBvKATKbQHD7hRErsA
      token-duration: 1D

server:
  port: 7050

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
