spring:
  application:
    name: auth-service

  data:
    mongodb:
      # Injected from K8s Secret via env var
      uri: ${MONGO_URI}

  jackson:
    serialization:
      indent_output: true

  security:
    jwt:
      # Injected from K8s Secret via env var
      secret-key: ${JWT_SECRET_KEY}
      token-duration: 1D

server:
  port: 7075

eureka:
  client:
    service-url:
      default-zone: http://registry-service:8761/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
