spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: supplier-route
          uri: lb://supplier-service
          predicates:
            - Path=/matchx/api/suppliers/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: supplierCircuitBreaker
                fallbackUri: forward:/fallback/suppliers

resilience4j:
  circuitbreaker:
    instances:
      supplierCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
