spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - name: AuthenticationFilter
      routes:
        - id: supplier-route
          uri: lb://supplier-service
          predicates:
            - Path=/matchx/api/suppliers/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: supplierCircuitBreaker
                fallbackUri: forward:/fallback/suppliers

        - id: product-route
          uri: lb://product-service
          predicates:
            - Path=/matchx/api/products/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: productCircuitBreaker
                fallbackUri: forward:/fallback/products

        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/matchx/api/orders/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallback/orders

        - id: order-matching-route
          uri: lb://order-matching-service
          predicates:
            - Path=/matchx/api/order-matching/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: orderMatchingCircuitBreaker
                fallbackUri: forward:/fallback/orderMatching

resilience4j:
  circuitbreaker:
    instances:
      supplierCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

      productCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

      orderCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

      orderMatchingCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: your-secret-key-here # Replace with your actual secret

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
