spring:
  application:
    name: order-matching-service

  devtools:
    restart:
      enabled: true  

logging:
  level:
    com.capstone.scloud: DEBUG 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka server URL
    register-with-eureka: true  
    fetch-registry: false       

  instance:
    prefer-ip-address: true     
